/** Auto-generated by scripts/sync-medium-from-rss.mjs — do not edit manually */

export const mediumPosts = [
  {
    "slug": "how-does-the-future-of-automation-look-29c93486cbe6",
    "title": "How Does the Future of Automation Look?",
    "date": "2026-04-19",
    "excerpt": "I spend my nights writing code designed to optimize systems, yet I often pause to consider the end game of the scripts I build. The logic is always the same: reduce friction, remov…",
    "readTime": "3 min read",
    "url": "https://medium.com/@thabheloduve/how-does-the-future-of-automation-look-29c93486cbe6",
    "coverImage": "https://cdn-images-1.medium.com/max/1024/1*UjpJLYjR05kgOETJ7uHNpA.png",
    "tags": [
      "Medium",
      "Tech"
    ],
    "channel": "medium"
  },
  {
    "slug": "microsoft-sql-server-on-macos-using-docker-d3d44e300f1b",
    "title": "Microsoft SQL Server on macOS using Docker",
    "date": "2026-01-27",
    "excerpt": "This document is a complete, repeatable guide for installing and running Microsoft SQL Server 2022 on macOS using Docker, and connecting to it with Azure Data Studio . It applies t…",
    "readTime": "3 min read",
    "url": "https://medium.com/@thabheloduve/microsoft-sql-server-on-macos-using-docker-d3d44e300f1b",
    "coverImage": "/media/blog-learning-code.jpg",
    "tags": [
      "Medium",
      "Tech"
    ],
    "channel": "medium"
  },
  {
    "slug": "fixing-screen-size-issues-in-kali-linux-on-virtualbox-apple-silicon-acc75d941ed1",
    "title": "Fixing Screen Size Issues in Kali Linux on VirtualBox (Apple Silicon)",
    "date": "2026-01-23",
    "excerpt": "Fixing Screen Size Issues in Linux on VirtualBox (Apple Silicon) Hi. If you’re running Kali Linux on VirtualBox on an Apple Silicon Mac (M1, M2, M3) , you’ll likely hit an annoying…",
    "readTime": "1 min read",
    "url": "https://medium.com/@thabheloduve/fixing-screen-size-issues-in-kali-linux-on-virtualbox-apple-silicon-acc75d941ed1",
    "coverImage": "https://cdn-images-1.medium.com/max/1024/1*J2A7qVD57qiiy9UBX03uHw.png",
    "tags": [
      "Medium",
      "Tech"
    ],
    "channel": "medium"
  },
  {
    "slug": "comprehensive-software-testing-theory-and-practice-for-python-72978c1e927a",
    "title": "Comprehensive Software Testing Theory and Practice for Python…",
    "date": "2025-07-01",
    "excerpt": "Comprehensive Software Testing Theory and Practice for Python ======================================================= Software testing represents a critical discipline bridging the…",
    "readTime": "21 min read",
    "url": "https://medium.com/@thabheloduve/comprehensive-software-testing-theory-and-practice-for-python-72978c1e927a",
    "coverImage": "https://cdn-images-1.medium.com/max/1024/1*pdamVXG3zdsI-iec90Qo5w.png",
    "tags": [
      "Medium",
      "Tech"
    ],
    "channel": "medium"
  },
  {
    "slug": "this-new-word-is-needed-now-more-than-ever-before-transphasophobia-0ad9918927e3",
    "title": "This new word is needed now more than ever before: Transphasophobia",
    "date": "2024-12-10",
    "excerpt": "In this our new world where artificial intelligence (AI) and digital media are reshaping how we experience visual and auditory content, we’re witnessing a new kind of discomfort: t…",
    "readTime": "6 min read",
    "url": "https://medium.com/@thabheloduve/this-new-word-is-needed-now-more-than-ever-before-transphasophobia-0ad9918927e3",
    "coverImage": "/media/blog-mdx-writing.jpg",
    "tags": [
      "Medium",
      "Tech"
    ],
    "channel": "medium"
  },
  {
    "slug": "here-are-one-line-solutions-for-leetcode-in-python-6e9727acc43d",
    "title": "Here are one-line solutions for Leetcode — in Python.",
    "date": "2024-07-24",
    "excerpt": "Here are one-line solutions for Leetcode — in Python. Hey fam! So I just thought of something. You may remember that Python is widely considered one of the best programming languag…",
    "readTime": "3 min read",
    "url": "https://medium.com/@thabheloduve/here-are-one-line-solutions-for-leetcode-in-python-6e9727acc43d",
    "coverImage": "https://cdn-images-1.medium.com/max/1024/1*OY3UUgpTsmZqYkVbSlb6uw.png",
    "tags": [
      "Medium",
      "Tech"
    ],
    "channel": "medium"
  },
  {
    "slug": "how-i-am-elevating-in-flight-health-monitoring-with-machine-learning-and-spatial-computing-apple-579eb291fd67",
    "title": "How I am elevating in-flight Health Monitoring with Machine Learning and Spatial Computing (Apple…",
    "date": "2024-07-17",
    "excerpt": "How I am elevating in-flight Health Monitoring with Machine Learning and Spatial Computing (Apple Vision Pro) In my last post, I introduced noVision, a Vision OS app aimed at enhan…",
    "readTime": "4 min read",
    "url": "https://medium.com/@thabheloduve/how-i-am-elevating-in-flight-health-monitoring-with-machine-learning-and-spatial-computing-apple-579eb291fd67",
    "coverImage": "https://cdn-images-1.medium.com/max/1024/1*fqtLW-Oxp5DdUoI3LRO5ww.png",
    "tags": [
      "Medium",
      "Tech"
    ],
    "channel": "medium"
  },
  {
    "slug": "shipping-my-new-visionos-app-novision-2884d859b7f7",
    "title": "Shipping My New VisionOS App: novision",
    "date": "2024-06-17",
    "excerpt": "Hello, fam! Its Thabhelo. So I thought of shipping my latest project, novision . I just decided it would be cool to have my personal platform to organize my coding tasks and track…",
    "readTime": "4 min read",
    "url": "https://medium.com/@thabheloduve/shipping-my-new-visionos-app-novision-2884d859b7f7",
    "coverImage": "https://cdn-images-1.medium.com/max/1024/1*I0YnuwvDWRrnqqqxtoPf3w.png",
    "tags": [
      "Medium",
      "Tech"
    ],
    "channel": "medium"
  },
  {
    "slug": "why-is-everyone-so-thrilled-and-excited-on-linkedin-all-the-time-363c01e58ba9",
    "title": "Why is everyone so “thrilled” and \"excited\" on LinkedIn all the time?",
    "date": "2023-10-15",
    "excerpt": "Ah, LinkedIn, the land of endless professional possibilities and polished profiles. Have you ever noticed that it seems like everyone on this platform is perpetually thrilled and e…",
    "readTime": "3 min read",
    "url": "https://medium.com/@thabheloduve/why-is-everyone-so-thrilled-and-excited-on-linkedin-all-the-time-363c01e58ba9",
    "coverImage": "/media/blog-mdx-writing.jpg",
    "tags": [
      "Medium",
      "Tech"
    ],
    "channel": "medium"
  }
] as const;

export type MediumPostConfig = (typeof mediumPosts)[number];
